#ifndef TEXTURE_UNITS_H
#define TEXTURE_UNITS_H

#define TU_TERRAINMESH_HEIGHT 0
#define TU_TERRAINMESH_MATERIAL 1
#define TU_MATERIAL_COLOR 2

//temp
#define TU_WATER_REFLECTIVE 3

#endif //TEXTURE_UNITS_H